version: 1
agent:
  clone:
    depth: 1
    ref:
      name: main
      type: branch
    repo: hello-world
  stages:
    - name: test_mcp
      id: stage1
      steps:
        - id: run_mcp_agent
          name: Run MCP Agent
          agent:
            container:
              connector: account.harnessImage
              image: docker.io/anewdocker25/cc_mcp:v1
            env:
              ANTHROPIC_MODEL: arn:aws:bedrock:us-east-1:587817102444:application-inference-profile/7p8sn93lhspw
              AWS_BEARER_TOKEN_BEDROCK: <+secrets.getValue("aws_bedrock_claude_code_ha")>
              AWS_REGION: us-east-1
              CLAUDE_CODE_USE_BEDROCK: "1"
            task: you have access to harnes mcp and tell me what all the tools you have access to. use some get tools to test that harness mcp server is working
            max_turns: 250
            mcp_servers:
              harness:
                url: https://88b7-34-93-204-95.ngrok-free.app/mcp
            with:
              allowed_tools: Read,Edit,Bash,Glob,Grep,Write,mcp__harness__*
              log_file: .agent/output/mcp-test-log.jsonl
              use_bedrock: "true"
      platform:
        os: linux
        arch: arm64
