pipeline:
  stages:
    - name: Stage
      id: stage
      steps:
        - name: Harness
          approval:
            with:
              message: This looks good
              execution-details: false
              auto-reject: false
              user-groups:
                - _project_all_users
              approvers-min-count: 1
              block-executor: false
              auto-approve: false
              inputs: {}
            uses: harness
          id: harness
